#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x96a8727e, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2b2ce672, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x537143a2, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x7067aec8, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x49cb6da6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x5fec3501, __VMLINUX_SYMBOL_STR(stp_proto_unregister) },
	{ 0x1fb53e8a, __VMLINUX_SYMBOL_STR(sysfs_remove_bin_file) },
	{ 0x20eadeb6, __VMLINUX_SYMBOL_STR(ip_compute_csum) },
	{ 0x45044497, __VMLINUX_SYMBOL_STR(percpu_counter_destroy) },
	{ 0x7b52e38, __VMLINUX_SYMBOL_STR(rtnl_unregister) },
	{ 0x91eb9b4, __VMLINUX_SYMBOL_STR(round_jiffies) },
	{ 0x3872b82c, __VMLINUX_SYMBOL_STR(netdev_notice) },
	{ 0xc996d097, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xb360e4, __VMLINUX_SYMBOL_STR(dev_get_flags) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x6b10cb77, __VMLINUX_SYMBOL_STR(dev_disable_lro) },
	{ 0x1e61779e, __VMLINUX_SYMBOL_STR(unregister_net_sysctl_table) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xd067fc5c, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0x6360b5ee, __VMLINUX_SYMBOL_STR(netdev_rx_handler_register) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x2fee0820, __VMLINUX_SYMBOL_STR(__skb_dst_set_noref) },
	{ 0x3f11799a, __VMLINUX_SYMBOL_STR(kobject_uevent) },
	{ 0x436e0d4c, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0xed62492e, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x1637ff0f, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x1f998cd7, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x2124474, __VMLINUX_SYMBOL_STR(ip_send_check) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x5fd41a36, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0xa2cfa00d, __VMLINUX_SYMBOL_STR(rtnl_notify) },
	{ 0xe7a664c4, __VMLINUX_SYMBOL_STR(nf_hooks) },
	{ 0x949f7342, __VMLINUX_SYMBOL_STR(__alloc_percpu) },
	{ 0x4a5c4c4, __VMLINUX_SYMBOL_STR(call_netdevice_notifiers) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xb6d765a8, __VMLINUX_SYMBOL_STR(kobject_del) },
	{ 0x433a7a77, __VMLINUX_SYMBOL_STR(neigh_destroy) },
	{ 0xf499fdb2, __VMLINUX_SYMBOL_STR(rcu_barrier_bh) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf51bf88b, __VMLINUX_SYMBOL_STR(nf_hooks_needed) },
	{ 0x51b9a7be, __VMLINUX_SYMBOL_STR(sysfs_remove_group) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0x30fd978d, __VMLINUX_SYMBOL_STR(nf_hook_slow) },
	{ 0x81a4fc20, __VMLINUX_SYMBOL_STR(skb_trim) },
	{ 0xdc9f40d5, __VMLINUX_SYMBOL_STR(kobject_create_and_add) },
	{ 0xcd08467e, __VMLINUX_SYMBOL_STR(ip_options_rcv_srr) },
	{ 0xa40abcde, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_link) },
	{ 0xcfd3f49d, __VMLINUX_SYMBOL_STR(__netdev_alloc_skb) },
	{ 0x27c33efe, __VMLINUX_SYMBOL_STR(csum_ipv6_magic) },
	{ 0x389d8a67, __VMLINUX_SYMBOL_STR(netif_rx) },
	{ 0x6db09e88, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xd5f2172f, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xcf163081, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x9fdecc31, __VMLINUX_SYMBOL_STR(unregister_netdevice_many) },
	{ 0x9adb23e7, __VMLINUX_SYMBOL_STR(sysfs_rename_link_ns) },
	{ 0xeb3df98c, __VMLINUX_SYMBOL_STR(stp_proto_register) },
	{ 0xa47329ed, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x93441f91, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0x71954cbd, __VMLINUX_SYMBOL_STR(sysfs_create_group) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x194912a7, __VMLINUX_SYMBOL_STR(inet_select_addr) },
	{        0, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0x2a86bdb8, __VMLINUX_SYMBOL_STR(__skb_warn_lro_forwarding) },
	{ 0xb3b3aaa2, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0xcd279169, __VMLINUX_SYMBOL_STR(nla_find) },
	{ 0x3116e63b, __VMLINUX_SYMBOL_STR(__ethtool_get_settings) },
	{ 0x66c34200, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0xa11036fc, __VMLINUX_SYMBOL_STR(llc_mac_hdr_init) },
	{ 0x32092db8, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0x436cc7a7, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0xb760b2dc, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0x9cf8db50, __VMLINUX_SYMBOL_STR(netdev_upper_dev_unlink) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x80bf2b5f, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe5a9fc63, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xd0f484f6, __VMLINUX_SYMBOL_STR(rtnl_register) },
	{ 0xf4f14de6, __VMLINUX_SYMBOL_STR(rtnl_trylock) },
	{ 0xc5fdef94, __VMLINUX_SYMBOL_STR(call_usermodehelper) },
	{ 0x8834396c, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x903caeb4, __VMLINUX_SYMBOL_STR(rtnl_af_unregister) },
	{ 0x97b167f3, __VMLINUX_SYMBOL_STR(sysfs_remove_link) },
	{ 0x3839bcd1, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0xf578befb, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x70d053fd, __VMLINUX_SYMBOL_STR(try_to_del_timer_sync) },
	{ 0x8d510973, __VMLINUX_SYMBOL_STR(rtnl_link_unregister) },
	{ 0xbf0a76af, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x5d089d74, __VMLINUX_SYMBOL_STR(nf_unregister_hooks) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x693477f4, __VMLINUX_SYMBOL_STR(ipv6_dev_get_saddr) },
	{ 0xf8b98ca6, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0x98ea1569, __VMLINUX_SYMBOL_STR(ip_route_input_noref) },
	{ 0xc17c8e2b, __VMLINUX_SYMBOL_STR(rtnl_set_sk_err) },
	{ 0x70eec980, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x8451b9a3, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0xd27088cf, __VMLINUX_SYMBOL_STR(ipv6_skip_exthdr) },
	{ 0xc2742a0d, __VMLINUX_SYMBOL_STR(rtnl_af_register) },
	{ 0xba63339c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x4f391d0e, __VMLINUX_SYMBOL_STR(nla_parse) },
	{ 0xb9249d16, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x43feab6b, __VMLINUX_SYMBOL_STR(netdev_rx_handler_unregister) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x763bbd23, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0xb6cee584, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0x2a79f3ff, __VMLINUX_SYMBOL_STR(brioctl_set) },
	{ 0xbb6c6951, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xdd641bb1, __VMLINUX_SYMBOL_STR(pskb_expand_head) },
	{ 0x6e297a62, __VMLINUX_SYMBOL_STR(__percpu_counter_init) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x397ad3bb, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0xf6ff814f, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0xa24a5360, __VMLINUX_SYMBOL_STR(__dev_get_by_name) },
	{ 0x2d9ab9bd, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3928efe9, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xd7e9215e, __VMLINUX_SYMBOL_STR(skb_pull_rcsum) },
	{ 0x46585bbe, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x59e2743e, __VMLINUX_SYMBOL_STR(call_rcu_bh) },
	{ 0xc84c59da, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0xd46c323, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x61f9fa1c, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x72d76dc2, __VMLINUX_SYMBOL_STR(___pskb_trim) },
	{ 0x1ec0fb0e, __VMLINUX_SYMBOL_STR(ip_options_compile) },
	{ 0xe63fa42a, __VMLINUX_SYMBOL_STR(nf_register_hooks) },
	{ 0xb754929a, __VMLINUX_SYMBOL_STR(sysfs_create_bin_file) },
	{ 0xb3faa28c, __VMLINUX_SYMBOL_STR(rtnl_link_register) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x7d0db45c, __VMLINUX_SYMBOL_STR(jiffies_to_clock_t) },
	{ 0xe113bbbc, __VMLINUX_SYMBOL_STR(csum_partial) },
	{ 0xfd277b5a, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0xd1ec9e28, __VMLINUX_SYMBOL_STR(netdev_update_features) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0xf42509c2, __VMLINUX_SYMBOL_STR(sysfs_create_file_ns) },
	{ 0x3141aa3d, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x2d25578c, __VMLINUX_SYMBOL_STR(register_net_sysctl) },
	{ 0x7c11b010, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x3f3afd1d, __VMLINUX_SYMBOL_STR(__nlmsg_put) },
	{ 0x62fe2bae, __VMLINUX_SYMBOL_STR(skb_copy_bits) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0xc58a8cd, __VMLINUX_SYMBOL_STR(netdev_increment_features) },
	{ 0xf6d712d, __VMLINUX_SYMBOL_STR(dev_set_mtu) },
	{ 0xd1bb14f1, __VMLINUX_SYMBOL_STR(__skb_checksum_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=stp,llc";


MODULE_INFO(srcversion, "55EE3458505D3065703AAEB");
